### ISSUE TITLE
Review the overall structure of the library and the interactions between functions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#10] opened 2019-07-29 15:34 UTC
@kindly had some concerns about the global variable for the database connection and cursor, I think.

**Comment by jpmckinney** [comment] 2020-04-18 19:18
Closing as the issue is a little too unspecific. I think the global variable is fine in the context of a notebook.

**Closed by jpmckinney** 2020-04-18 19:18 UTC
Labels: cleanup
